### PR TITLE
simplify number of imports needed when importing keypairs

### LINKED ISSUE #11: Decouple `ZkLogin` from `Ed25519PublicKey` and others `*PublicKey`
## Steps to Reproduce Issue

In the current implementation, `*PublicKey` classes pull the `ZkLogin` dependency, which in turn pulls `SuiGraphQLClient`.

This is a lot of extra code that is not needed to work without `ZkLogin` features.

https://github.com/MystenLabs/ts-sdks/blob/577746c3089327b16d7fa3edab13e47dac0e2db2/packages/typescript/src/keypairs/ed25519/publickey.ts#L70

https://github.com/MystenLabs/ts-sdks/blob/577746c3089327b16d7fa3edab13e47dac0e2db2/packages/typescript/src/cryptography/signature.ts#L52-L70

https://github.com/MystenLabs/ts-sdks/blob/577746c3089327b16d7fa3edab13e47dac0e2db2/packages/typescript/src/zklogin/publickey.ts#L11-L12

### PR DESCRIPTION
**Pull request by hayes-mysten**
## Description

fixes #11 

## Test plan

How did you test the new or updated feature?

---

### CODE REVIEW

**Review by Jordan-Mysten — APPROVED** [review]

**Review by williamrobertson13 — APPROVED** [review]

File: packages/build-scripts/src/utils/buildPackage.ts [hunk 1]
```diff
@@ -171,7 +171,7 @@ async function buildImportDirectories({ exports, sideEffects }: PackageJSON) {
 
 async function createEmptyDir(path: string) {
 	if (existsSync(path)) {
-		await fs.rm(path, { recursive: true, force: true });
+		await fs.rm(path, { recursive: true, force: true, maxRetries: 5 });
```
Comment (hayes-mysten) [inline packages/build-scripts/src/utils/buildPackage.ts:174]: Been seeing some weird failures here where deleting fails because the directory isn't empty....
